#pragma once
#include <array>

/**
 * Uniform matrices, use for testing correctness
 */
extern const std::array<std::array<float, 20>, 20> test_mu_small;
extern const std::array<float, 20> test_solution_small;
extern const std::array<std::array<float, 50>, 50> test_mu_normal;
extern const std::array<float, 50> test_solution_normal;
extern const std::array<std::array<float, 60>, 60> test_mu_big;
extern const std::array<float, 60> test_solution_big;

/**
 * Knapsack matrices generated by latticegen
 */
extern const std::array<std::array<float, 40>, 40> test_mu_knapsack_normal;
extern const std::array<std::array<float, 50>, 50> test_mu_knapsack_big;

/**
 * Up to orthogonal transform equal to test_mu_knapsack_big. This is the result of
 * the fplll preprocessing on test_mu_knapsack_big, so use this to compare performance.
 */
extern const std::array<std::array<float, 50>, 50> test_mu_compare;
extern const std::array<float, 50> test_rdiag_compare;