name: Basic no-GPU Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: nvidia/cuda:11.2.2-devel-ubuntu20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: ./configure CUDA_CFLAGS="-D TEST_CPU_ONLY" CFLAGS="-D TEST_CPU_ONLY"
    - name: Build
      run: make cudaenum_test
    - name: Test
      run: ./cudaenum_test