name: Basic no-GPU Test

on:
  push:
    branches: [ FeanorTheElf-CI ]
  pull_request:
    branches: [ FeanorTheElf-CI ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: nvidia/cuda:11.2.2-devel-ubuntu20.04
    steps:
    - name: list
      run: ls /github/workspace
    - name: Build and Test
      run: make cputest
