name: Basic no-GPU Test

on:
  push:
    branches: [ FeanorTheElf-CI ]
  pull_request:
    branches: [ FeanorTheElf-CI ]

jobs:
  test_no_gpu:
    runs-on: ubuntu-latest
    container: nvidia/cuda:11.2.2-devel-ubuntu20.04
    steps:
    - name: build_and_test
      run: make cputest
