name: C/C++ CI

on:
  push:
    branches: [ FeanorTheElf-CI ]
  pull_request:
    branches: [ FeanorTheElf-CI ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make cputest
